''' 
#######################################################################################################

AUTHOR:             Adam Dynamic
CONTACT:            helloadamdynamic@gmail.com / www.adamdynamic.com
LAST REVISION:      28 December 2013

PROJECT:            Tube Challenge Route Creation
DESCRIPTION:        Contains static data used by other modules in calculations 

#######################################################################################################
'''

TOTAL_NUMBER_OF_STATIONS = 267 

# Values used in the calculation of distances
DEFAULT_DISTANCE_TO_STREET = 2
DEFAULT_LINE_CHANGE = 5
DEFAULT_STATION_WAIT = 0.333 # Assume 20 seconds wait at each station

# Define the database access details
DB_HOST = "localhost"
DB_USER = "username"
DB_PASSWORD = "password"
DB_NAME = "LondonUnderground"

# Define the names of tables in the database
DB_TABLE_DISTANCES_COMPLETE = "tbl_StationDistancesComplete"
DB_TABLE_SUMMARY_STATS= "`tbl_SummaryStats`"
DB_TABLE_SHORTEST_ROUTE = "`tbl_ShortestRoute`"

# Column names for the Stations distances table
DISTCOMP_FIELD_STATIONTO = "`StationFrom`"
DISTCOMP_FIELD_STATIONFROM = "`StationTo`"
DISTCOMP_FIELD_STATIONLINE = "`Line`"
DISTCOMP_FIELD_DISTANCE = "`Distance`"

# Column names for the Summary Stats table
SUMSTAT_FIELD_TIMESLOT = "`TimeSlot`"
SUMSTAT_FIELD_FREQ = "`Frequency`"

# Column names for the Shortest Route table
SHORTROUTE_DISTANCE = "`Distance`"
SHORTROUTE_DESC_LONG = "`RouteDescription_Long`"
SHORTROUTE_DESC_LIST = "`RouteDescription_List`"
SHORTROUTE_DATETIME = "`DateTime`"


CSV_FILE_PATH = "LondonUndergroundEdited_WithWalkingAndTrains.csv"

# Times from each station to all connecting stations
# Peak times only were taken from the original TFL .csv file
# Times between stations do not take any account of times taken to change lines, walk to the street from the platform, waits on the platform etc
STATIONS_DISTANCES_PEAK = {
                        'ACTON TOWN' : {'CHISWICK PARK': 2.0, 'HAMMERSMITH': 5.53, 'EALING COMMON': 2.01, 'SOUTH EALING': 3.02},
                        'ALDGATE' : {'LIVERPOOL STREET': 2.38, 'TOWER HILL': 2.1, 'ALDGATE EAST': 3.0},
                        'ALDGATE EAST' : {'WHITECHAPEL': 2.01, 'LIVERPOOL STREET': 2.5, 'TOWER HILL': 3.65, 'ALDGATE': 3.0},
                        'ALPERTON' : {'SUDBURY TOWN': 2.5, 'PARK ROYAL': 2.5},
                        'AMERSHAM' : {'CHALFONT & LATIMER': 4.0},
                        'ANGEL' : {'OLD STREET': 3.0, 'KINGS CROSS ST PANCRAS': 2.5},
                        'ARCHWAY' : {'HIGHGATE': 3.0, 'TUFNELL PARK': 1.5},
                        'ARNOS GROVE' : {'TOTTERIDGE & WHETSTONE': 11.0, 'BOUNDS GREEN': 2.0, 'SOUTHGATE': 2.51},
                        'ARSENAL' : {'HOLLOWAY ROAD': 1.5, 'FINSBURY PARK': 1.5},
                        'BAKER STREET' : {'MARYLEBONE': 1.5, 'EDGWARE ROAD': 3.08, 'BOND STREET': 2.5, 'REGENTS PARK': 2.0, 'FINCHLEY ROAD': 5.51, 'GREAT PORTLAND STREET': 2.0, 'ST JOHNS WOOD': 3.5},
                        'BALHAM' : {'CLAPHAM SOUTH': 2.0, 'TOOTING BEC': 2.0},
                        'BANK' : {'LIVERPOOL STREET': 2.25, 'WATERLOO': 3.75, 'ST PAULS': 2.0, 'LONDON BRIDGE': 2.0, 'MOORGATE': 2.01, 'MONUMENT': 5.0},
                        'BARBICAN' : {'ST PAULS': 9.0, 'MOORGATE': 1.5, 'FARRINGDON': 1.5},
                        'BARKING' : {'UPNEY': 2.01, 'EAST HAM': 3.5, 'WALTHAMSTOW': 24.0, 'LEYTONSTONE': 20.0},
                        'BARKINGSIDE' : {'NEWBURY PARK': 2.35, 'FAIRLOP': 1.79},
                        'BARONS COURT' : {'HAMMERSMITH': 1.5, 'EARLS COURT': 3.0, 'WEST KENSINGTON': 1.5},
                        'BAYSWATER' : {'PADDINGTON': 2.01, 'NOTTING HILL GATE': 2.0, 'QUEENSWAY': 2.0},
                        'BECONTREE' : {'UPNEY': 2.5, 'DAGENHAM HEATHWAY': 2.51},
                        'BELSIZE PARK' : {'WEST HAMPSTEAD': 14.0, 'CHALK FARM': 2.0, 'HAMPSTEAD': 2.5},
                        'BERMONDSEY' : {'LONDON BRIDGE': 2.5, 'CANADA WATER': 2.0},
                        'BETHNAL GREEN' : {'LIVERPOOL STREET': 3.25, 'MILE END': 2.25},
                        'BLACKFRIARS' : {'TEMPLE': 1.5, 'MANSION HOUSE': 1.52},
                        'BLACKHORSE ROAD' : {'TOTTENHAM HALE': 2.0, 'TUFNELL PARK': 30.0, 'WALTHAMSTOW': 2.01},
                        'BOND STREET' : {'OXFORD CIRCUS': 1.5, 'BAKER STREET': 2.5, 'GREEN PARK': 2.5, 'MARBLE ARCH': 1.5},
                        'BOROUGH' : {'LONDON BRIDGE': 1.5, 'ELEPHANT & CASTLE': 2.0},
                        'BOSTON MANOR' : {'OSTERLEY': 3.0, 'NORTHFIELDS': 3.38},
                        'BOUNDS GREEN' : {'WOOD GREEN': 2.57, 'ARNOS GROVE': 3.91},
                        'BOW ROAD' : {'MILE END': 1.5, 'BROMLEY BY BOW': 2.0},
                        'BRENT CROSS' : {'GOLDERS GREEN': 3.64, 'HENDON CENTRAL': 2.0},
                        'BRIXTON' : {'STOCKWELL': 2.0},
                        'BROMLEY BY BOW' : {'BOW ROAD': 2.5, 'WEST HAM': 2.0},
                        'BUCKHURST HILL' : {'LOUGHTON': 2.53, 'WOODFORD': 2.53},
                        'BURNT OAK' : {'COLINDALE': 2.5, 'EDGWARE': 3.6},
                        'CALEDONIAN ROAD' : {'HOLLOWAY ROAD': 1.5, 'KINGS CROSS ST PANCRAS': 3.52},
                        'CAMDEN TOWN' : {'CHALK FARM': 1.5, 'EUSTON': 3.55, 'MORNINGTON CRESCENT': 1.5, 'HIGHBURY': 11.0, 'KENTISH TOWN': 2.0},
                        'CANADA WATER' : {'CLAPHAM NORTH': 20.0, 'WHITECHAPEL': 7.0, 'CANARY WHARF': 3.02, 'BERMONDSEY': 2.0},
                        'CANARY WHARF' : {'NORTH GREENWICH': 3.49, 'CANADA WATER': 3.0},
                        'CANNING TOWN' : {'NORTH GREENWICH': 2.99, 'WEST HAM': 2.58},
                        'CANNON STREET' : {'MANSION HOUSE': 1.5, 'MONUMENT': 1.5},
                        'CANONS PARK' : {'EDGWARE': 6.0, 'QUEENSBURY': 2.5, 'HARROW & WEALDSTONE': 20.0, 'STANMORE': 3.09},
                        'CHALFONT & LATIMER' : {'AMERSHAM': 4.0, 'CHORLEYWOOD': 4.0, 'CHESHAM': 8.5},
                        'CHALK FARM' : {'BELSIZE PARK': 2.0, 'CAMDEN TOWN': 2.56},
                        'CHANCERY LANE' : {'ST PAULS': 2.0, 'HOLBORN': 1.25, 'FARRINGDON': 8.0},
                        'CHARING CROSS' : {'PICCADILLY CIRCUS': 2.0, 'EMBANKMENT': 1.0, 'LEICESTER SQUARE': 1.5},
                        'CHESHAM' : {'CHALFONT & LATIMER': 8.5},
                        'CHIGWELL' : {'GRANGE HILL': 2.11, 'RODING VALLEY': 2.5},
                        'CHISWICK PARK' : {'ACTON TOWN': 2.06, 'TURNHAM GREEN': 2.09},
                        'CHORLEYWOOD' : {'RICKMANSWORTH': 4.58, 'CHALFONT & LATIMER': 4.5},
                        'CLAPHAM COMMON' : {'CLAPHAM NORTH': 1.5, 'CLAPHAM SOUTH': 2.5},
                        'CLAPHAM NORTH' : {'CLAPHAM COMMON': 1.5, 'CANADA WATER': 20.0, 'STOCKWELL': 2.0},
                        'CLAPHAM SOUTH' : {'CLAPHAM COMMON': 2.5, 'BALHAM': 2.0},
                        'COCKFOSTERS' : {'HIGH BARNET': 22.0, 'OAKWOOD': 2.45},
                        'COLINDALE' : {'BURNT OAK': 2.0, 'HENDON CENTRAL': 3.0},
                        'COLLIERS WOOD' : {'SOUTH WIMBLEDON': 2.0, 'TOOTING BROADWAY': 2.0},
                        'COVENT GARDEN' : {'HOLBORN': 1.5, 'LEICESTER SQUARE': 1.0},
                        'CROXLEY' : {'MOOR PARK': 4.0, 'WATFORD': 3.5},
                        'DAGENHAM EAST' : {'DAGENHAM HEATHWAY': 2.0, 'ELM PARK': 3.0},
                        'DAGENHAM HEATHWAY' : {'BECONTREE': 2.5, 'DAGENHAM EAST': 2.3},
                        'DEBDEN' : {'LOUGHTON': 3.4, 'THEYDON BOIS': 3.0},
                        'DOLLIS HILL' : {'WILLESDEN GREEN': 2.14, 'NEASDEN': 1.5},
                        'EALING BROADWAY' : {'WEST ACTON': 2.25, 'NORTH EALING': 12.0, 'EALING COMMON': 3.0},
                        'EALING COMMON' : {'EALING BROADWAY': 3.54, 'NORTH EALING': 2.0, 'ACTON TOWN': 3.45},
                        'EARLS COURT' : {'WEST BROMPTON': 1.5, 'KENSINGTON (OLYMPIA)': 3.0, 'BARONS COURT': 3.0, 'WEST KENSINGTON': 2.0, 'HIGH STREET KENSINGTON': 3.12, 'GLOUCESTER ROAD': 1.5},
                        'EAST ACTON' : {'WHITE CITY': 3.71, 'NORTH ACTON': 2.54},
                        'EAST FINCHLEY' : {'HIGHGATE': 3.0, 'FINCHLEY CENTRAL': 4.26},
                        'EAST HAM' : {'UPTON PARK': 2.0, 'BARKING': 3.49},
                        'EAST PUTNEY' : {'PUTNEY BRIDGE': 2.0, 'SOUTHFIELDS': 2.5},
                        'EASTCOTE' : {'RAYNERS LANE': 3.95, 'RUISLIP MANOR': 2.0},
                        'EDGWARE' : {'BURNT OAK': 2.5, 'CANONS PARK': 6.0},
                        'EDGWARE ROAD' : {'MARYLEBONE': 1.5, 'PADDINGTON': 2.0, 'BAKER STREET': 2.5},
                        'ELEPHANT & CASTLE' : {'LAMBETH NORTH': 2.0, 'BOROUGH': 2.0, 'KENNINGTON': 3.47},
                        'ELM PARK' : {'HORNCHURCH': 2.5, 'DAGENHAM EAST': 3.18},
                        'EMBANKMENT' : {'WESTMINSTER': 1.5, 'CHARING CROSS': 1.0, 'WATERLOO': 1.5, 'TEMPLE': 2.0},
                        'EPPING' : {'THEYDON BOIS': 2.5},
                        'EUSTON' : {'MORNINGTON CRESCENT': 1.5, 'WARREN STREET': 1.5, 'EUSTON SQUARE': 5.0, 'KINGS CROSS ST PANCRAS': 2.0, 'CAMDEN TOWN': 4.02},
                        'EUSTON SQUARE' : {'EUSTON': 5.0, 'WARREN STREET': 3.0, 'GREAT PORTLAND STREET': 1.5, 'KINGS CROSS ST PANCRAS': 2.0},
                        'FAIRLOP' : {'BARKINGSIDE': 1.75, 'HAINAULT': 4.12},
                        'FARRINGDON' : {'BARBICAN': 1.5, 'KINGS CROSS ST PANCRAS': 3.5, 'CHANCERY LANE': 8.0},
                        'FINCHLEY CENTRAL' : {'MILL HILL EAST': 2.5, 'WEST FINCHLEY': 2.0, 'EAST FINCHLEY': 3.5},
                        'FINCHLEY ROAD' : {'WEST HAMPSTEAD': 1.51, 'WEMBLEY PARK': 7.0, 'BAKER STREET': 6.4, 'HARROW-ON-THE-HILL': 11.0, 'SWISS COTTAGE': 1.5},
                        'FINSBURY PARK' : {'HIGHBURY': 2.55, 'MANOR HOUSE': 2.0, 'ARSENAL': 1.5, 'SEVEN SISTERS': 5.76},
                        'FULHAM BROADWAY' : {'PARSONS GREEN': 2.0, 'WEST BROMPTON': 1.5},
                        'GANTS HILL' : {'NEWBURY PARK': 2.98, 'REDBRIDGE': 2.0},
                        'GLOUCESTER ROAD' : {'HIGH STREET KENSINGTON': 2.92, 'EARLS COURT': 1.5, 'SOUTH KENSINGTON': 1.5},
                        'GOLDERS GREEN' : {'BRENT CROSS': 2.5, 'HAMPSTEAD': 3.5},
                        'GOLDHAWK ROAD' : {'HAMMERSMITH': 3.03, 'SHEPHERDS BUSH MARKET': 1.5},
                        'GOODGE STREET' : {'WARREN STREET': 1.5, 'TOTTENHAM COURT ROAD': 1.5},
                        'GRANGE HILL' : {'CHIGWELL': 2.0, 'HAINAULT': 4.32},
                        'GREAT PORTLAND STREET' : {'REGENTS PARK': 3.0, 'EUSTON SQUARE': 1.5, 'WARREN STREET': 6.0, 'BAKER STREET': 3.82},
                        'GREEN PARK' : {'OXFORD CIRCUS': 2.02, 'PICCADILLY CIRCUS': 1.5, 'BOND STREET': 2.5, 'VICTORIA': 2.54, 'WESTMINSTER': 2.5, 'HYDE PARK CORNER': 2.02},
                        'GREENFORD' : {'NORTHOLT': 2.28, 'PERIVALE': 2.25},
                        'GUNNERSBURY' : {'TURNHAM GREEN': 3.67, 'KEW GARDENS': 2.5, 'WILLESDEN JUNCTION': 12.0},
                        'HAINAULT' : {'GRANGE HILL': 1.79, 'FAIRLOP': 2.0},
                        'HAMMERSMITH' : {'GOLDHAWK ROAD': 2.0, 'RAVENSCOURT PARK': 2.0, 'ACTON TOWN': 6.87, 'BARONS COURT': 2.0},
                        'HAMPSTEAD' : {'BELSIZE PARK': 2.0, 'GOLDERS GREEN': 5.36},
                        'HANGER LANE' : {'PARK ROYAL': 10.0, 'PERIVALE': 2.25, 'NORTH ACTON': 3.48},
                        'HARLESDEN' : {'STONEBRIDGE PARK': 2.53, 'WILLESDEN JUNCTION': 2.23},
                        'HARROW & WEALDSTONE' : {'KENTON': 2.5, 'CANONS PARK': 20.0},
                        'HARROW-ON-THE-HILL' : {'MOOR PARK': 9.5, 'NORTHWICK PARK': 2.0, 'FINCHLEY ROAD': 11.5, 'NORTH HARROW': 3.0, 'WEST HARROW': 2.0},
                        'HATTON CROSS' : {'HEATHROW TERMINAL FOUR': 2.5, 'HEATHROW 123': 4.0, 'HOUNSLOW WEST': 3.5},
                        'HEATHROW 123' : {'HEATHROW 5': 3.5, 'HATTON CROSS': 3.0},
                        'HEATHROW 5' : {'HEATHROW 123': 4.0},
                        'HEATHROW TERMINAL FOUR' : {'HEATHROW 123': 5.0},
                        'HENDON CENTRAL' : {'BRENT CROSS': 2.0, 'COLINDALE': 3.0},
                        'HIGH BARNET' : {'TOTTERIDGE & WHETSTONE': 3.5, 'COCKFOSTERS': 22.0},
                        'HIGH STREET KENSINGTON' : {'NOTTING HILL GATE': 2.0, 'EARLS COURT': 3.82, 'GLOUCESTER ROAD': 2.9},
                        'HIGHBURY' : {'WHITECHAPEL': 13.0, 'STRATFORD': 17.0, 'CAMDEN TOWN': 11.0, 'KINGS CROSS ST PANCRAS': 3.5, 'FINSBURY PARK': 2.56},
                        'HIGHGATE' : {'ARCHWAY': 3.0, 'EAST FINCHLEY': 3.0},
                        'HILLINGDON' : {'UXBRIDGE': 3.5, 'ICKENHAM': 2.0},
                        'HOLBORN' : {'COVENT GARDEN': 2.0, 'TOTTENHAM COURT ROAD': 1.75, 'CHANCERY LANE': 1.0, 'RUSSELL SQUARE': 2.0},
                        'HOLLAND PARK' : {'SHEPHERDS BUSH': 1.75, 'NOTTING HILL GATE': 1.5},
                        'HOLLOWAY ROAD' : {'ARSENAL': 1.5, 'CALEDONIAN ROAD': 1.5},
                        'HORNCHURCH' : {'UPMINSTER BRIDGE': 2.0, 'ELM PARK': 2.5},
                        'HOUNSLOW CENTRAL' : {'HOUNSLOW WEST': 2.0, 'HOUNSLOW EAST': 1.5},
                        'HOUNSLOW EAST' : {'HOUNSLOW CENTRAL': 1.5, 'OSTERLEY': 2.0},
                        'HOUNSLOW WEST' : {'HOUNSLOW CENTRAL': 2.5, 'HATTON CROSS': 5.5},
                        'HYDE PARK CORNER' : {'KNIGHTSBRIDGE': 1.5, 'GREEN PARK': 2.02},
                        'ICKENHAM' : {'HILLINGDON': 2.0, 'WEST RUISLIP': 13.0, 'RUISLIP': 2.5},
                        'KENNINGTON' : {'OVAL': 2.0, 'WATERLOO': 3.0, 'ELEPHANT & CASTLE': 2.0},
                        'KENSAL GREEN' : {'QUEENS PARK': 4.72, 'WILLESDEN JUNCTION': 3.15},
                        'KENSINGTON (OLYMPIA)' : {'SHEPHERDS BUSH': 7.0, 'EARLS COURT': 3.94, 'WEST BROMPTON': 3.0},
                        'KENTISH TOWN' : {'CAMDEN TOWN': 3.08, 'TUFNELL PARK': 1.5},
                        'KENTON' : {'HARROW & WEALDSTONE': 3.0, 'SOUTH KENTON': 2.0, 'NORTHWICK PARK': 6.0},
                        'KEW GARDENS' : {'RICHMOND': 3.5, 'GUNNERSBURY': 3.0},
                        'KILBURN' : {'WEST HAMPSTEAD': 2.0, 'WILLESDEN GREEN': 2.22},
                        'KILBURN PARK' : {'MAIDA VALE': 2.0, 'QUEENS PARK': 2.89},
                        'KINGS CROSS ST PANCRAS' : {'FARRINGDON': 3.5, 'ANGEL': 2.5, 'HIGHBURY': 3.0, 'EUSTON SQUARE': 2.0, 'RUSSELL SQUARE': 2.0, 'EUSTON': 1.52, 'CALEDONIAN ROAD': 3.5},
                        'KINGSBURY' : {'QUEENSBURY': 2.0, 'WEMBLEY PARK': 4.56},
                        'KNIGHTSBRIDGE' : {'SOUTH KENSINGTON': 2.5, 'HYDE PARK CORNER': 1.5},
                        'LADBROKE GROVE' : {'LATIMER ROAD': 1.5, 'WESTBOURNE PARK': 1.5},
                        'LAMBETH NORTH' : {'WATERLOO': 2.06, 'ELEPHANT & CASTLE': 2.5},
                        'LANCASTER GATE' : {'PADDINGTON': 8.0, 'MARBLE ARCH': 2.5, 'QUEENSWAY': 1.75},
                        'LATIMER ROAD' : {'LADBROKE GROVE': 1.5, 'WOOD LANE': 1.5},
                        'LEICESTER SQUARE' : {'CHARING CROSS': 1.5, 'TOTTENHAM COURT ROAD': 1.5, 'PICCADILLY CIRCUS': 1.5, 'COVENT GARDEN': 1.01},
                        'LEYTON' : {'STRATFORD': 2.75, 'LEYTONSTONE': 2.76},
                        'LEYTONSTONE' : {'WANSTEAD': 2.25, 'SNARESBROOK': 2.25, 'LEYTON': 2.25, 'WALTHAMSTOW': 17.0, 'BARKING': 20.0},
                        'LIVERPOOL STREET' : {'BETHNAL GREEN': 2.75, 'ALDGATE': 2.2, 'MOORGATE': 1.5, 'BANK': 2.0, 'ALDGATE EAST': 2.78},
                        'LONDON BRIDGE' : {'SOUTHWARK': 2.0, 'BERMONDSEY': 2.5, 'BANK': 2.0, 'BOROUGH': 1.5},
                        'LOUGHTON' : {'DEBDEN': 2.25, 'BUCKHURST HILL': 2.5},
                        'MAIDA VALE' : {'KILBURN PARK': 1.5, 'WARWICK AVENUE': 1.5},
                        'MANOR HOUSE' : {'TURNPIKE LANE': 3.0, 'FINSBURY PARK': 2.0},
                        'MANSION HOUSE' : {'ST PAULS': 6.0, 'BLACKFRIARS': 1.5, 'CANNON STREET': 1.0},
                        'MARBLE ARCH' : {'LANCASTER GATE': 2.0, 'BOND STREET': 1.25},
                        'MARYLEBONE' : {'BAKER STREET': 1.5, 'EDGWARE ROAD': 1.0},
                        'MILE END' : {'BETHNAL GREEN': 2.25, 'STEPNEY GREEN': 2.0, 'STRATFORD': 3.25, 'BOW ROAD': 1.5},
                        'MILL HILL EAST' : {'FINCHLEY CENTRAL': 3.0},
                        'MONUMENT' : {'BANK': 5.0, 'CANNON STREET': 1.0, 'TOWER HILL': 2.43},
                        'MOOR PARK' : {'NORTHWOOD': 3.0, 'RICKMANSWORTH': 5.0, 'HARROW-ON-THE-HILL': 10.0, 'CROXLEY': 4.5},
                        'MOORGATE' : {'BARBICAN': 1.5, 'LIVERPOOL STREET': 1.53, 'OLD STREET': 1.5, 'BANK': 2.0},
                        'MORDEN' : {'SOUTH WIMBLEDON': 2.5, 'WIMBLEDON': 15.0},
                        'MORNINGTON CRESCENT' : {'EUSTON': 2.0, 'CAMDEN TOWN': 2.04},
                        'NEASDEN' : {'DOLLIS HILL': 1.5, 'WEMBLEY PARK': 3.53},
                        'NEWBURY PARK' : {'GANTS HILL': 3.0, 'BARKINGSIDE': 1.75},
                        'NORTH ACTON' : {'WEST ACTON': 2.76, 'EAST ACTON': 1.75, 'HANGER LANE': 3.0},
                        'NORTH EALING' : {'WEST ACTON': 10.0, 'EALING BROADWAY': 12.0, 'PARK ROYAL': 2.0, 'EALING COMMON': 2.5},
                        'NORTH GREENWICH' : {'CANARY WHARF': 2.5, 'CANNING TOWN': 2.5},
                        'NORTH HARROW' : {'HARROW-ON-THE-HILL': 4.49, 'PINNER': 2.5},
                        'NORTH WEMBLEY' : {'WEMBLEY CENTRAL': 2.06, 'SOUTH KENTON': 1.5},
                        'NORTHFIELDS' : {'BOSTON MANOR': 2.0, 'SOUTH EALING': 1.5},
                        'NORTHOLT' : {'SOUTH RUISLIP': 2.5, 'GREENFORD': 2.0},
                        'NORTHWICK PARK' : {'KENTON': 6.0, 'HARROW-ON-THE-HILL': 3.03, 'PRESTON ROAD': 2.0},
                        'NORTHWOOD' : {'MOOR PARK': 3.0, 'NORTHWOOD HILLS': 2.5},
                        'NORTHWOOD HILLS' : {'PINNER': 2.5, 'NORTHWOOD': 2.5},
                        'NOTTING HILL GATE' : {'BAYSWATER': 2.0, 'HOLLAND PARK': 1.5, 'HIGH STREET KENSINGTON': 3.36, 'QUEENSWAY': 1.5},
                        'OAKWOOD' : {'SOUTHGATE': 2.5, 'COCKFOSTERS': 3.09},
                        'OLD STREET' : {'ANGEL': 2.5, 'MOORGATE': 1.51},
                        'OSTERLEY' : {'BOSTON MANOR': 3.0, 'HOUNSLOW EAST': 2.0},
                        'OVAL' : {'KENNINGTON': 2.91, 'STOCKWELL': 2.5},
                        'OXFORD CIRCUS' : {'PICCADILLY CIRCUS': 2.48, 'BOND STREET': 1.25, 'WARREN STREET': 2.04, 'GREEN PARK': 2.04, 'REGENTS PARK': 2.0, 'TOTTENHAM COURT ROAD': 1.5},
                        'PADDINGTON' : {'BAYSWATER': 2.0, 'ROYAL OAK': 1.5, 'WARWICK AVENUE': 2.0, 'EDGWARE ROAD': 3.72, 'LANCASTER GATE': 8.0},
                        'PARK ROYAL' : {'NORTH EALING': 2.03, 'ALPERTON': 2.5, 'HANGER LANE': 10.0},
                        'PARSONS GREEN' : {'PUTNEY BRIDGE': 2.5, 'FULHAM BROADWAY': 2.0},
                        'PERIVALE' : {'GREENFORD': 2.25, 'HANGER LANE': 2.26},
                        'PICCADILLY CIRCUS' : {'CHARING CROSS': 1.5, 'OXFORD CIRCUS': 2.19, 'GREEN PARK': 1.5, 'LEICESTER SQUARE': 1.5},
                        'PIMLICO' : {'VAUXHALL': 1.54, 'VICTORIA': 2.51},
                        'PINNER' : {'NORTH HARROW': 2.5, 'NORTHWOOD HILLS': 2.5},
                        'PLAISTOW' : {'UPTON PARK': 2.0, 'WEST HAM': 1.5},
                        'PRESTON ROAD' : {'WEMBLEY PARK': 2.53, 'NORTHWICK PARK': 2.5},
                        'PUTNEY BRIDGE' : {'PARSONS GREEN': 2.0, 'EAST PUTNEY': 2.0},
                        'QUEENS PARK' : {'KILBURN PARK': 1.5, 'KENSAL GREEN': 2.72},
                        'QUEENSBURY' : {'CANONS PARK': 2.5, 'KINGSBURY': 2.0},
                        'QUEENSWAY' : {'NOTTING HILL GATE': 1.5, 'LANCASTER GATE': 1.5, 'BAYSWATER': 2.0},
                        'RAVENSCOURT PARK' : {'HAMMERSMITH': 2.0, 'STAMFORD BROOK': 1.5},
                        'RAYNERS LANE' : {'SOUTH HARROW': 4.46, 'EASTCOTE': 2.5, 'WEST HARROW': 2.0},
                        'REDBRIDGE' : {'WANSTEAD': 1.75, 'GANTS HILL': 1.75},
                        'REGENTS PARK' : {'OXFORD CIRCUS': 2.0, 'BAKER STREET': 2.0, 'GREAT PORTLAND STREET': 3.0},
                        'RICHMOND' : {'KEW GARDENS': 3.0},
                        'RICKMANSWORTH' : {'CHORLEYWOOD': 4.0, 'MOOR PARK': 4.5},
                        'RODING VALLEY' : {'CHIGWELL': 2.25, 'WOODFORD': 2.22},
                        'ROYAL OAK' : {'PADDINGTON': 2.0, 'WARWICK AVENUE': 12.0, 'WESTBOURNE PARK': 2.0},
                        'RUISLIP' : {'RUISLIP MANOR': 1.5, 'WEST RUISLIP': 16.0, 'ICKENHAM': 2.5},
                        'RUISLIP GARDENS' : {'SOUTH RUISLIP': 1.5, 'WEST RUISLIP': 2.75},
                        'RUISLIP MANOR' : {'EASTCOTE': 2.0, 'RUISLIP': 1.5},
                        'RUSSELL SQUARE' : {'HOLBORN': 1.5, 'KINGS CROSS ST PANCRAS': 2.05},
                        'SEVEN SISTERS' : {'TOTTENHAM HALE': 1.5, 'FINSBURY PARK': 4.0},
                        'SHEPHERDS BUSH' : {'WILLESDEN JUNCTION': 12.0, 'HOLLAND PARK': 1.75, 'WHITE CITY': 3.97, 'KENSINGTON (OLYMPIA)': 7.0, 'SHEPHERDS BUSH MARKET': 7.0},
                        'SHEPHERDS BUSH MARKET' : {'GOLDHAWK ROAD': 1.0, 'SHEPHERDS BUSH': 7.0, 'WOOD LANE': 1.5},
                        'SLOANE SQUARE' : {'SOUTH KENSINGTON': 2.5, 'VICTORIA': 2.0},
                        'SNARESBROOK' : {'SOUTH WOODFORD': 1.75, 'LEYTONSTONE': 3.33},
                        'SOUTH EALING' : {'ACTON TOWN': 4.28, 'NORTHFIELDS': 1.98},
                        'SOUTH HARROW' : {'RAYNERS LANE': 3.06, 'SUDBURY HILL': 2.0},
                        'SOUTH KENSINGTON' : {'KNIGHTSBRIDGE': 3.0, 'GLOUCESTER ROAD': 1.5, 'SLOANE SQUARE': 2.0},
                        'SOUTH KENTON' : {'KENTON': 2.0, 'NORTH WEMBLEY': 1.5},
                        'SOUTH RUISLIP' : {'RUISLIP GARDENS': 1.54, 'NORTHOLT': 2.5},
                        'SOUTH WIMBLEDON' : {'MORDEN': 3.56, 'COLLIERS WOOD': 2.0},
                        'SOUTH WOODFORD' : {'SNARESBROOK': 1.75, 'WOODFORD': 2.26},
                        'SOUTHFIELDS' : {'EAST PUTNEY': 2.5, 'WIMBLEDON PARK': 2.51},
                        'SOUTHGATE' : {'ARNOS GROVE': 4.35, 'OAKWOOD': 3.51},
                        'SOUTHWARK' : {'LONDON BRIDGE': 2.5, 'WATERLOO': 1.5},
                        'ST JAMES PARK' : {'WESTMINSTER': 2.0, 'VICTORIA': 2.0},
                        'ST JOHNS WOOD' : {'BAKER STREET': 3.5, 'SWISS COTTAGE': 1.5},
                        'ST PAULS' : {'BARBICAN': 9.0, 'CHANCERY LANE': 1.75, 'BANK': 2.0, 'MANSION HOUSE': 6.0},
                        'STAMFORD BROOK' : {'RAVENSCOURT PARK': 1.5, 'TURNHAM GREEN': 1.58},
                        'STANMORE' : {'CANONS PARK': 2.0},
                        'STEPNEY GREEN' : {'WHITECHAPEL': 2.56, 'MILE END': 2.0},
                        'STOCKWELL' : {'CLAPHAM NORTH': 1.5, 'OVAL': 2.5, 'BRIXTON': 2.5, 'VAUXHALL': 2.5},
                        'STONEBRIDGE PARK' : {'HARLESDEN': 2.4, 'WEMBLEY CENTRAL': 3.17},
                        'STRATFORD' : {'HIGHBURY': 17.0, 'LEYTON': 2.75, 'MILE END': 3.0, 'WEST HAM': 3.12},
                        'SUDBURY HILL' : {'SUDBURY TOWN': 2.5, 'SOUTH HARROW': 2.75},
                        'SUDBURY TOWN' : {'ALPERTON': 2.5, 'SUDBURY HILL': 2.5},
                        'SWISS COTTAGE' : {'FINCHLEY ROAD': 2.0, 'ST JOHNS WOOD': 2.0},
                        'TEMPLE' : {'BLACKFRIARS': 2.0, 'EMBANKMENT': 2.0},
                        'THEYDON BOIS' : {'DEBDEN': 3.25, 'EPPING': 2.75},
                        'TOOTING BEC' : {'BALHAM': 2.0, 'TOOTING BROADWAY': 2.0},
                        'TOOTING BROADWAY' : {'COLLIERS WOOD': 2.0, 'TOOTING BEC': 2.0},
                        'TOTTENHAM COURT ROAD' : {'GOODGE STREET': 1.5, 'OXFORD CIRCUS': 1.5, 'HOLBORN': 2.01, 'LEICESTER SQUARE': 1.0},
                        'TOTTENHAM HALE' : {'SEVEN SISTERS': 3.28, 'BLACKHORSE ROAD': 2.5},
                        'TOTTERIDGE & WHETSTONE' : {'WOODSIDE PARK': 2.5, 'ARNOS GROVE': 11.0, 'HIGH BARNET': 4.5},
                        'TOWER HILL' : {'ALDGATE': 3.18, 'ALDGATE EAST': 2.21, 'MONUMENT': 1.5},
                        'TUFNELL PARK' : {'BLACKHORSE ROAD': 30.0, 'KENTISH TOWN': 1.5, 'ARCHWAY': 2.0},
                        'TURNHAM GREEN' : {'CHISWICK PARK': 2.0, 'GUNNERSBURY': 3.0, 'STAMFORD BROOK': 1.5},
                        'TURNPIKE LANE' : {'WOOD GREEN': 2.02, 'MANOR HOUSE': 3.0},
                        'UPMINSTER' : {'UPMINSTER BRIDGE': 2.03},
                        'UPMINSTER BRIDGE' : {'HORNCHURCH': 2.0, 'UPMINSTER': 2.01},
                        'UPNEY' : {'BECONTREE': 2.51, 'BARKING': 3.82},
                        'UPTON PARK' : {'PLAISTOW': 2.5, 'EAST HAM': 2.0},
                        'UXBRIDGE' : {'HILLINGDON': 3.0},
                        'VAUXHALL' : {'PIMLICO': 1.5, 'STOCKWELL': 2.52},
                        'VICTORIA' : {'ST JAMES PARK': 1.5, 'PIMLICO': 2.0, 'SLOANE SQUARE': 2.0, 'GREEN PARK': 2.0},
                        'WALTHAMSTOW' : {'BLACKHORSE ROAD': 2.0, 'BARKING': 24.0, 'LEYTONSTONE': 17.0},
                        'WANSTEAD' : {'REDBRIDGE': 2.0, 'LEYTONSTONE': 3.64},
                        'WARREN STREET' : {'GOODGE STREET': 1.5, 'EUSTON': 1.5, 'EUSTON SQUARE': 3.0, 'OXFORD CIRCUS': 2.0, 'GREAT PORTLAND STREET': 6.0},
                        'WARWICK AVENUE' : {'PADDINGTON': 2.0, 'MAIDA VALE': 1.5, 'ROYAL OAK': 12.0},
                        'WATERLOO' : {'SOUTHWARK': 1.0, 'KENNINGTON': 3.4, 'WESTMINSTER': 2.01, 'EMBANKMENT': 2.0, 'LAMBETH NORTH': 2.0, 'BANK': 4.0},
                        'WATFORD' : {'CROXLEY': 3.0},
                        'WEMBLEY CENTRAL' : {'STONEBRIDGE PARK': 3.13, 'NORTH WEMBLEY': 2.0},
                        'WEMBLEY PARK' : {'FINCHLEY ROAD': 7.52, 'NEASDEN': 3.01, 'KINGSBURY': 4.0, 'PRESTON ROAD': 2.5},
                        'WEST ACTON' : {'EALING BROADWAY': 2.82, 'NORTH EALING': 10.0, 'NORTH ACTON': 3.26},
                        'WEST BROMPTON' : {'FULHAM BROADWAY': 1.5, 'KENSINGTON (OLYMPIA)': 3.0, 'EARLS COURT': 3.24},
                        'WEST FINCHLEY' : {'WOODSIDE PARK': 2.0, 'FINCHLEY CENTRAL': 2.51},
                        'WEST HAM' : {'PLAISTOW': 2.04, 'CANNING TOWN': 2.5, 'STRATFORD': 3.77, 'BROMLEY BY BOW': 2.0},
                        'WEST HAMPSTEAD' : {'BELSIZE PARK': 14.0, 'KILBURN': 2.0, 'WILLESDEN JUNCTION': 8.0, 'FINCHLEY ROAD': 1.5},
                        'WEST HARROW' : {'RAYNERS LANE': 2.5, 'HARROW-ON-THE-HILL': 4.0},
                        'WEST KENSINGTON' : {'EARLS COURT': 3.3, 'BARONS COURT': 1.5},
                        'WEST RUISLIP' : {'RUISLIP GARDENS': 2.5, 'ICKENHAM': 13.0, 'RUISLIP': 16.0},
                        'WESTBOURNE PARK' : {'ROYAL OAK': 2.0, 'LADBROKE GROVE': 1.5},
                        'WESTMINSTER' : {'ST JAMES PARK': 1.5, 'WATERLOO': 2.0, 'EMBANKMENT': 2.0, 'GREEN PARK': 2.01},
                        'WHITE CITY' : {'SHEPHERDS BUSH': 2.75, 'EAST ACTON': 3.0, 'WOOD LANE': 3.0},
                        'WHITECHAPEL' : {'STEPNEY GREEN': 2.0, 'CANADA WATER': 7.0, 'HIGHBURY': 13.0, 'ALDGATE EAST': 2.06},
                        'WILLESDEN GREEN' : {'DOLLIS HILL': 2.0, 'KILBURN': 2.0},
                        'WILLESDEN JUNCTION' : {'WEST HAMPSTEAD': 8.0, 'HARLESDEN': 2.0, 'GUNNERSBURY': 12.0, 'SHEPHERDS BUSH': 12.0, 'KENSAL GREEN': 2.5},
                        'WIMBLEDON' : {'MORDEN': 15.0, 'WIMBLEDON PARK': 3.0},
                        'WIMBLEDON PARK' : {'SOUTHFIELDS': 2.0, 'WIMBLEDON': 3.08},
                        'WOOD GREEN' : {'BOUNDS GREEN': 2.5, 'TURNPIKE LANE': 1.5},
                        'WOOD LANE' : {'LATIMER ROAD': 1.5, 'WHITE CITY': 3.0, 'SHEPHERDS BUSH MARKET': 1.5},
                        'WOODFORD' : {'SOUTH WOODFORD': 2.25, 'BUCKHURST HILL': 2.5, 'RODING VALLEY': 2.5},
                        'WOODSIDE PARK' : {'TOTTERIDGE & WHETSTONE': 2.5, 'WEST FINCHLEY': 1.5}
                      }

# Complete ordered list of all stations on the London Underground
STATIONS_COMPLETE = [
                        'ACTON TOWN',
                        'ALDGATE',
                        'ALDGATE EAST',
                        'ALPERTON',
                        'AMERSHAM',
                        'ANGEL',
                        'ARCHWAY',
                        'ARNOS GROVE',
                        'ARSENAL',
                        'BAKER STREET',
                        'BALHAM',
                        'BANK',
                        'BARBICAN',
                        'BARKING',
                        'BARKINGSIDE',
                        'BARONS COURT',
                        'BAYSWATER',
                        'BECONTREE',
                        'BELSIZE PARK',
                        'BERMONDSEY',
                        'BETHNAL GREEN',
                        'BLACKFRIARS',
                        'BLACKHORSE ROAD',
                        'BOND STREET',
                        'BOROUGH',
                        'BOSTON MANOR',
                        'BOUNDS GREEN',
                        'BOW ROAD',
                        'BRENT CROSS',
                        'BRIXTON',
                        'BROMLEY BY BOW',
                        'BUCKHURST HILL',
                        'BURNT OAK',
                        'CALEDONIAN ROAD',
                        'CAMDEN TOWN',
                        'CANADA WATER',
                        'CANARY WHARF',
                        'CANNING TOWN',
                        'CANNON STREET',
                        'CANONS PARK',
                        'CHALFONT & LATIMER',
                        'CHALK FARM',
                        'CHANCERY LANE',
                        'CHARING CROSS',
                        'CHESHAM',
                        'CHIGWELL',
                        'CHISWICK PARK',
                        'CHORLEYWOOD',
                        'CLAPHAM COMMON',
                        'CLAPHAM NORTH',
                        'CLAPHAM SOUTH',
                        'COCKFOSTERS',
                        'COLINDALE',
                        'COLLIERS WOOD',
                        'COVENT GARDEN',
                        'CROXLEY',
                        'DAGENHAM EAST',
                        'DAGENHAM HEATHWAY',
                        'DEBDEN',
                        'DOLLIS HILL',
                        'EALING BROADWAY',
                        'EALING COMMON',
                        'EARLS COURT',
                        'EAST ACTON',
                        'EAST FINCHLEY',
                        'EAST HAM',
                        'EAST PUTNEY',
                        'EASTCOTE',
                        'EDGWARE',
                        'EDGWARE ROAD',
                        'ELEPHANT & CASTLE',
                        'ELM PARK',
                        'EMBANKMENT',
                        'EPPING',
                        'EUSTON',
                        'EUSTON SQUARE',
                        'FAIRLOP',
                        'FARRINGDON',
                        'FINCHLEY CENTRAL',
                        'FINCHLEY ROAD',
                        'FINSBURY PARK',
                        'FULHAM BROADWAY',
                        'GANTS HILL',
                        'GLOUCESTER ROAD',
                        'GOLDERS GREEN',
                        'GOLDHAWK ROAD',
                        'GOODGE STREET',
                        'GRANGE HILL',
                        'GREAT PORTLAND STREET',
                        'GREEN PARK',
                        'GREENFORD',
                        'GUNNERSBURY',
                        'HAINAULT',
                        'HAMMERSMITH',
                        'HAMPSTEAD',
                        'HANGER LANE',
                        'HARLESDEN',
                        'HARROW & WEALDSTONE',
                        'HARROW-ON-THE-HILL',
                        'HATTON CROSS',
                        'HEATHROW 123',
                        'HEATHROW 5',
                        'HEATHROW TERMINAL FOUR',
                        'HENDON CENTRAL',
                        'HIGH BARNET',
                        'HIGH STREET KENSINGTON',
                        'HIGHBURY',
                        'HIGHGATE',
                        'HILLINGDON',
                        'HOLBORN',
                        'HOLLAND PARK',
                        'HOLLOWAY ROAD',
                        'HORNCHURCH',
                        'HOUNSLOW CENTRAL',
                        'HOUNSLOW EAST',
                        'HOUNSLOW WEST',
                        'HYDE PARK CORNER',
                        'ICKENHAM',
                        'KENNINGTON',
                        'KENSAL GREEN',
                        'KENSINGTON (OLYMPIA)',
                        'KENTISH TOWN',
                        'KENTON',
                        'KEW GARDENS',
                        'KILBURN',
                        'KILBURN PARK',
                        'KINGS CROSS ST PANCRAS',
                        'KINGSBURY',
                        'KNIGHTSBRIDGE',
                        'LADBROKE GROVE',
                        'LAMBETH NORTH',
                        'LANCASTER GATE',
                        'LATIMER ROAD',
                        'LEICESTER SQUARE',
                        'LEYTON',
                        'LEYTONSTONE',
                        'LIVERPOOL STREET',
                        'LONDON BRIDGE',
                        'LOUGHTON',
                        'MAIDA VALE',
                        'MANOR HOUSE',
                        'MANSION HOUSE',
                        'MARBLE ARCH',
                        'MARYLEBONE',
                        'MILE END',
                        'MILL HILL EAST',
                        'MONUMENT',
                        'MOOR PARK',
                        'MOORGATE',
                        'MORDEN',
                        'MORNINGTON CRESCENT',
                        'NEASDEN',
                        'NEWBURY PARK',
                        'NORTH ACTON',
                        'NORTH EALING',
                        'NORTH GREENWICH',
                        'NORTH HARROW',
                        'NORTH WEMBLEY',
                        'NORTHFIELDS',
                        'NORTHOLT',
                        'NORTHWICK PARK',
                        'NORTHWOOD',
                        'NORTHWOOD HILLS',
                        'NOTTING HILL GATE',
                        'OAKWOOD',
                        'OLD STREET',
                        'OSTERLEY',
                        'OVAL',
                        'OXFORD CIRCUS',
                        'PADDINGTON',
                        'PARK ROYAL',
                        'PARSONS GREEN',
                        'PERIVALE',
                        'PICCADILLY CIRCUS',
                        'PIMLICO',
                        'PINNER',
                        'PLAISTOW',
                        'PRESTON ROAD',
                        'PUTNEY BRIDGE',
                        'QUEENS PARK',
                        'QUEENSBURY',
                        'QUEENSWAY',
                        'RAVENSCOURT PARK',
                        'RAYNERS LANE',
                        'REDBRIDGE',
                        'REGENTS PARK',
                        'RICHMOND',
                        'RICKMANSWORTH',
                        'RODING VALLEY',
                        'ROYAL OAK',
                        'RUISLIP',
                        'RUISLIP GARDENS',
                        'RUISLIP MANOR',
                        'RUSSELL SQUARE',
                        'SEVEN SISTERS',
                        'SHEPHERDS BUSH',
                        'SHEPHERDS BUSH MARKET',
                        'SLOANE SQUARE',
                        'SNARESBROOK',
                        'SOUTH EALING',
                        'SOUTH HARROW',
                        'SOUTH KENSINGTON',
                        'SOUTH KENTON',
                        'SOUTH RUISLIP',
                        'SOUTH WIMBLEDON',
                        'SOUTH WOODFORD',
                        'SOUTHFIELDS',
                        'SOUTHGATE',
                        'SOUTHWARK',
                        'ST JAMES PARK',
                        'ST JOHNS WOOD',
                        'ST PAULS',
                        'STAMFORD BROOK',
                        'STANMORE',
                        'STEPNEY GREEN',
                        'STOCKWELL',
                        'STONEBRIDGE PARK',
                        'STRATFORD',
                        'SUDBURY HILL',
                        'SUDBURY TOWN',
                        'SWISS COTTAGE',
                        'TEMPLE',
                        'THEYDON BOIS',
                        'TOOTING BEC',
                        'TOOTING BROADWAY',
                        'TOTTENHAM COURT ROAD',
                        'TOTTENHAM HALE',
                        'TOTTERIDGE & WHETSTONE',
                        'TOWER HILL',
                        'TUFNELL PARK',
                        'TURNHAM GREEN',
                        'TURNPIKE LANE',
                        'UPMINSTER',
                        'UPMINSTER BRIDGE',
                        'UPNEY',
                        'UPTON PARK',
                        'UXBRIDGE',
                        'VAUXHALL',
                        'VICTORIA',
                        'WALTHAMSTOW',
                        'WANSTEAD',
                        'WARREN STREET',
                        'WARWICK AVENUE',
                        'WATERLOO',
                        'WATFORD',
                        'WEMBLEY CENTRAL',
                        'WEMBLEY PARK',
                        'WEST ACTON',
                        'WEST BROMPTON',
                        'WEST FINCHLEY',
                        'WEST HAM',
                        'WEST HAMPSTEAD',
                        'WEST HARROW',
                        'WEST KENSINGTON',
                        'WEST RUISLIP',
                        'WESTBOURNE PARK',
                        'WESTMINSTER',
                        'WHITE CITY',
                        'WHITECHAPEL',
                        'WILLESDEN GREEN',
                        'WILLESDEN JUNCTION',
                        'WIMBLEDON',
                        'WIMBLEDON PARK',
                        'WOOD GREEN',
                        'WOOD LANE',
                        'WOODFORD',
                        'WOODSIDE PARK'
                     ]

# Contains all stations with either 1 or 3+ connecting stations (i.e. excludes stations on edges)
NODES_COMPLETE = [
                    'ACTON TOWN',
                    'ALDGATE',
                    'ALDGATE EAST',
                    'AMERSHAM',
                    'ARNOS GROVE',
                    'BAKER STREET',
                    'BANK',
                    'BARBICAN',
                    'BARKING',
                    'BARONS COURT',
                    'BAYSWATER',
                    'BELSIZE PARK',
                    'BLACKHORSE ROAD',
                    'BOND STREET',
                    'BRIXTON',
                    'CAMDEN TOWN',
                    'CANADA WATER',
                    'CANONS PARK',
                    'CHALFONT & LATIMER',
                    'CHANCERY LANE',
                    'CHARING CROSS',
                    'CHESHAM',
                    'CLAPHAM NORTH',
                    'COCKFOSTERS',
                    'EALING BROADWAY',
                    'EALING COMMON',
                    'EARLS COURT',
                    'EDGWARE',
                    'EDGWARE ROAD',
                    'ELEPHANT & CASTLE',
                    'EMBANKMENT',
                    'EPPING',
                    'EUSTON',
                    'EUSTON SQUARE',
                    'FARRINGDON',
                    'FINCHLEY CENTRAL',
                    'FINCHLEY ROAD',
                    'FINSBURY PARK',
                    'GLOUCESTER ROAD',
                    'GREAT PORTLAND STREET',
                    'GREEN PARK',
                    'GUNNERSBURY',
                    'HAMMERSMITH',
                    'HANGER LANE',
                    'HARROW & WEALDSTONE',
                    'HARROW-ON-THE-HILL',                    
                    'HATTON CROSS',
                    'HEATHROW 5',
                    'HEATHROW TERMINAL FOUR',
                    'HIGH BARNET',
                    'HIGH STREET KENSINGTON',
                    'HIGHBURY',
                    'HOLBORN',
                    'ICKENHAM',
                    'KENNINGTON',
                    'KENSINGTON (OLYMPIA)',
                    'KENTON',
                    'KINGS CROSS ST PANCRAS',
                    'LANCASTER GATE',
                    'LEICESTER SQUARE',
                    'LEYTONSTONE',
                    'LIVERPOOL STREET',
                    'LONDON BRIDGE',
                    'MANSION HOUSE',
                    'MILE END',
                    'MILL HILL EAST',
                    'MONUMENT',
                    'MOOR PARK',
                    'MOORGATE',
                    'MORDEN',
                    'NORTH ACTON',
                    'NORTH EALING',
                    'NORTHWICK PARK',
                    'NOTTING HILL GATE',
                    'OXFORD CIRCUS',
                    'PADDINGTON',
                    'PARK ROYAL',
                    'PICCADILLY CIRCUS',
                    'QUEENSWAY',
                    'RAYNERS LANE',
                    'REGENTS PARK',
                    'RICHMOND',
                    'ROYAL OAK',
                    'RUISLIP',
                    'SHEPHERDS BUSH',
                    'SHEPHERDS BUSH MARKET',
                    'SOUTH KENSINGTON',
                    'ST PAULS',
                    'STANMORE',
                    'STOCKWELL',
                    'STRATFORD',
                    'TOTTENHAM COURT ROAD',
                    'TOTTERIDGE & WHETSTONE',
                    'TOWER HILL',
                    'TUFNELL PARK',
                    'TURNHAM GREEN',
                    'UPMINSTER',
                    'UXBRIDGE',
                    'VICTORIA',
                    'WALTHAMSTOW',
                    'WARREN STREET',
                    'WARWICK AVENUE',
                    'WATERLOO',
                    'WATFORD',
                    'WEMBLEY PARK',
                    'WEST ACTON',
                    'WEST BROMPTON',
                    'WEST HAM',
                    'WEST HAMPSTEAD',
                    'WEST RUISLIP',
                    'WESTMINSTER',
                    'WHITE CITY',
                    'WHITECHAPEL',
                    'WILLESDEN JUNCTION',
                    'WIMBLEDON',
                    'WOOD LANE',
                    'WOODFORD'                       
                  ]

# Contains only those stations at the end of the line
NODES_SINGLE = [
                    'AMERSHAM', 
                    'BRIXTON', 
                    'CANONS PARK', 
                    'CHESHAM', 
                    'COCKFOSTERS', 
                    'EALING BROADWAY', 
                    'EDGWARE', 
                    'EPPING', 
                    'HARROW & WEALDSTONE', 
                    'HEATHROW 5', 
                    'HEATHROW TERMINAL FOUR', 
                    'HIGH BARNET', 
                    'MILL HILL EAST', 
                    'MORDEN', 
                    'RICHMOND', 
                    'STANMORE', 
                    'UPMINSTER', 
                    'UXBRIDGE', 
                    'WALTHAMSTOW', 
                    'WATFORD', 
                    'WEST RUISLIP', 
                    'WIMBLEDON'
                    ]

# Dictionary of all lines and the stations on each line
# The 'Bus' and 'Walking' lines were created manually by inspecting the tube map/researching the tube challenge and then google-mapping the distances, 
LINES_AND_STATIONS = {
                    'Bakerloo' : ['BAKER STREET', 'CHARING CROSS', 'EDGWARE ROAD', 'ELEPHANT & CASTLE', 'EMBANKMENT', 'HARLESDEN', 'HARROW & WEALDSTONE', 'KENSAL GREEN', 'KENTON', 'KILBURN PARK', 'LAMBETH NORTH', 'MAIDA VALE', 'MARYLEBONE', 'NORTH WEMBLEY', 'OXFORD CIRCUS', 'PADDINGTON', 'PICCADILLY CIRCUS', 'QUEENS PARK', 'REGENTS PARK', 'SOUTH KENTON', 'STONEBRIDGE PARK', 'WARWICK AVENUE', 'WATERLOO', 'WEMBLEY CENTRAL', 'WILLESDEN JUNCTION'],
                    'Bus' : ['ARNOS GROVE', 'CANONS PARK', 'COCKFOSTERS', 'EDGWARE', 'HARROW & WEALDSTONE', 'HIGH BARNET', 'LEYTONSTONE', 'MORDEN', 'TOTTERIDGE & WHETSTONE', 'WALTHAMSTOW', 'WIMBLEDON'],
                    'Central' : ['BANK', 'BARKINGSIDE', 'BETHNAL GREEN', 'BOND STREET', 'BUCKHURST HILL', 'CHANCERY LANE', 'CHIGWELL', 'DEBDEN', 'EALING BROADWAY', 'EAST ACTON', 'EPPING', 'FAIRLOP', 'GANTS HILL', 'GRANGE HILL', 'GREENFORD', 'HAINAULT', 'HANGER LANE', 'HOLBORN', 'HOLLAND PARK', 'LANCASTER GATE', 'LEYTON', 'LEYTONSTONE', 'LIVERPOOL STREET', 'LOUGHTON', 'MARBLE ARCH', 'MILE END', 'NEWBURY PARK', 'NORTH ACTON', 'NORTHOLT', 'NOTTING HILL GATE', 'OXFORD CIRCUS', 'PERIVALE', 'QUEENSWAY', 'REDBRIDGE', 'RODING VALLEY', 'RUISLIP GARDENS', 'SHEPHERDS BUSH', 'SNARESBROOK', 'SOUTH RUISLIP', 'SOUTH WOODFORD', 'ST PAULS', 'STRATFORD', 'THEYDON BOIS', 'TOTTENHAM COURT ROAD', 'WANSTEAD', 'WEST ACTON', 'WEST RUISLIP', 'WHITE CITY', 'WOODFORD'],
                    'Circle' : ['ALDGATE', 'BAKER STREET', 'BARBICAN', 'BAYSWATER', 'BLACKFRIARS', 'CANNON STREET', 'EDGWARE ROAD', 'EMBANKMENT', 'EUSTON SQUARE', 'FARRINGDON', 'GLOUCESTER ROAD', 'GOLDHAWK ROAD', 'GREAT PORTLAND STREET', 'HAMMERSMITH', 'HIGH STREET KENSINGTON', 'KINGS CROSS ST PANCRAS', 'LADBROKE GROVE', 'LATIMER ROAD', 'LIVERPOOL STREET', 'MANSION HOUSE', 'MONUMENT', 'MOORGATE', 'NOTTING HILL GATE', 'PADDINGTON', 'ROYAL OAK', 'SHEPHERDS BUSH MARKET', 'SLOANE SQUARE', 'SOUTH KENSINGTON', 'ST JAMES PARK', 'TEMPLE', 'TOWER HILL', 'VICTORIA', 'WESTBOURNE PARK', 'WESTMINSTER', 'WOOD LANE'],
                    'District' : ['ACTON TOWN', 'ALDGATE EAST', 'BARKING', 'BARONS COURT', 'BAYSWATER', 'BECONTREE', 'BLACKFRIARS', 'BOW ROAD', 'BROMLEY BY BOW', 'CANNON STREET', 'CHISWICK PARK', 'DAGENHAM EAST', 'DAGENHAM HEATHWAY', 'EALING BROADWAY', 'EALING COMMON', 'EARLS COURT', 'EAST HAM', 'EAST PUTNEY', 'EDGWARE ROAD', 'ELM PARK', 'EMBANKMENT', 'FULHAM BROADWAY', 'GLOUCESTER ROAD', 'GUNNERSBURY', 'HAMMERSMITH', 'HIGH STREET KENSINGTON', 'HORNCHURCH', 'KENSINGTON (OLYMPIA)', 'KEW GARDENS', 'MANSION HOUSE', 'MILE END', 'MONUMENT', 'NOTTING HILL GATE', 'PADDINGTON', 'PARSONS GREEN', 'PLAISTOW', 'PUTNEY BRIDGE', 'RAVENSCOURT PARK', 'RICHMOND', 'SLOANE SQUARE', 'SOUTH KENSINGTON', 'SOUTHFIELDS', 'ST JAMES PARK', 'STAMFORD BROOK', 'STEPNEY GREEN', 'TEMPLE', 'TOWER HILL', 'TURNHAM GREEN', 'UPMINSTER', 'UPMINSTER BRIDGE', 'UPNEY', 'UPTON PARK', 'VICTORIA', 'WEST BROMPTON', 'WEST HAM', 'WEST KENSINGTON', 'WESTMINSTER', 'WHITECHAPEL', 'WIMBLEDON', 'WIMBLEDON PARK'],
                    'H & C' : ['ALDGATE EAST', 'BAKER STREET', 'BARBICAN', 'BARKING', 'BOW ROAD', 'BROMLEY BY BOW', 'EAST HAM', 'EDGWARE ROAD', 'EUSTON SQUARE', 'FARRINGDON', 'GOLDHAWK ROAD', 'GREAT PORTLAND STREET', 'HAMMERSMITH', 'KINGS CROSS ST PANCRAS', 'LADBROKE GROVE', 'LATIMER ROAD', 'LIVERPOOL STREET', 'MILE END', 'MOORGATE', 'PADDINGTON', 'PLAISTOW', 'ROYAL OAK', 'SHEPHERDS BUSH MARKET', 'STEPNEY GREEN', 'UPTON PARK', 'WEST HAM', 'WESTBOURNE PARK', 'WHITECHAPEL', 'WOOD LANE'],
                    'Jubilee' : ['BAKER STREET', 'BERMONDSEY', 'BOND STREET', 'CANADA WATER', 'CANARY WHARF', 'CANNING TOWN', 'CANONS PARK', 'DOLLIS HILL', 'FINCHLEY ROAD', 'GREEN PARK', 'KILBURN', 'KINGSBURY', 'LONDON BRIDGE', 'NEASDEN', 'NORTH GREENWICH', 'QUEENSBURY', 'SOUTHWARK', 'ST JOHNS WOOD', 'STANMORE', 'STRATFORD', 'SWISS COTTAGE', 'WATERLOO', 'WEMBLEY PARK', 'WEST HAM', 'WEST HAMPSTEAD', 'WESTMINSTER', 'WILLESDEN GREEN'],
                    'Metropolitan' : ['ALDGATE', 'AMERSHAM', 'BAKER STREET', 'BARBICAN', 'CHALFONT & LATIMER', 'CHESHAM', 'CHORLEYWOOD', 'CROXLEY', 'EASTCOTE', 'EUSTON SQUARE', 'FARRINGDON', 'FINCHLEY ROAD', 'GREAT PORTLAND STREET', 'HARROW-ON-THE-HILL', 'HILLINGDON', 'ICKENHAM', 'KINGS CROSS ST PANCRAS', 'LIVERPOOL STREET', 'MOOR PARK', 'MOORGATE', 'NORTH HARROW', 'NORTHWICK PARK', 'NORTHWOOD', 'NORTHWOOD HILLS', 'PINNER', 'PRESTON ROAD', 'RAYNERS LANE', 'RICKMANSWORTH', 'RUISLIP', 'RUISLIP MANOR', 'UXBRIDGE', 'WATFORD', 'WEMBLEY PARK', 'WEST HARROW'],
                    'Northern' : ['ANGEL', 'ARCHWAY', 'BALHAM', 'BANK', 'BELSIZE PARK', 'BOROUGH', 'BRENT CROSS', 'BURNT OAK', 'CAMDEN TOWN', 'CHALK FARM', 'CHARING CROSS', 'CLAPHAM COMMON', 'CLAPHAM NORTH', 'CLAPHAM SOUTH', 'COLINDALE', 'COLLIERS WOOD', 'EAST FINCHLEY', 'EDGWARE', 'ELEPHANT & CASTLE', 'EMBANKMENT', 'EUSTON', 'FINCHLEY CENTRAL', 'GOLDERS GREEN', 'GOODGE STREET', 'HAMPSTEAD', 'HENDON CENTRAL', 'HIGH BARNET', 'HIGHGATE', 'KENNINGTON', 'KENTISH TOWN', 'KINGS CROSS ST PANCRAS', 'LEICESTER SQUARE', 'LONDON BRIDGE', 'MILL HILL EAST', 'MOORGATE', 'MORDEN', 'MORNINGTON CRESCENT', 'OLD STREET', 'OVAL', 'SOUTH WIMBLEDON', 'STOCKWELL', 'TOOTING BEC', 'TOOTING BROADWAY', 'TOTTENHAM COURT ROAD', 'TOTTERIDGE & WHETSTONE', 'TUFNELL PARK', 'WARREN STREET', 'WATERLOO', 'WEST FINCHLEY', 'WOODSIDE PARK'],
                    'Overland' : ['BARKING', 'BELSIZE PARK', 'BLACKHORSE ROAD', 'CAMDEN TOWN', 'CANADA WATER', 'CLAPHAM NORTH', 'GUNNERSBURY', 'HIGHBURY', 'KENSINGTON (OLYMPIA)', 'LEYTONSTONE', 'SHEPHERDS BUSH', 'STRATFORD', 'TUFNELL PARK', 'WALTHAMSTOW', 'WEST BROMPTON', 'WEST HAMPSTEAD', 'WHITECHAPEL', 'WILLESDEN JUNCTION'],
                    'Piccadilly' : ['ACTON TOWN', 'ALPERTON', 'ARNOS GROVE', 'ARSENAL', 'BARONS COURT', 'BOSTON MANOR', 'BOUNDS GREEN', 'CALEDONIAN ROAD', 'COCKFOSTERS', 'COVENT GARDEN', 'EALING COMMON', 'EARLS COURT', 'EASTCOTE', 'FINSBURY PARK', 'GLOUCESTER ROAD', 'GREEN PARK', 'HAMMERSMITH', 'HATTON CROSS', 'HEATHROW 123', 'HEATHROW 5', 'HEATHROW TERMINAL FOUR', 'HILLINGDON', 'HOLBORN', 'HOLLOWAY ROAD', 'HOUNSLOW CENTRAL', 'HOUNSLOW EAST', 'HOUNSLOW WEST', 'HYDE PARK CORNER', 'ICKENHAM', 'KINGS CROSS ST PANCRAS', 'KNIGHTSBRIDGE', 'LEICESTER SQUARE', 'MANOR HOUSE', 'NORTH EALING', 'NORTHFIELDS', 'OAKWOOD', 'OSTERLEY', 'PARK ROYAL', 'PICCADILLY CIRCUS', 'RAYNERS LANE', 'RUISLIP', 'RUISLIP MANOR', 'RUSSELL SQUARE', 'SOUTH EALING', 'SOUTH HARROW', 'SOUTH KENSINGTON', 'SOUTHGATE', 'SUDBURY HILL', 'SUDBURY TOWN', 'TURNPIKE LANE', 'UXBRIDGE', 'WOOD GREEN'],
                    'Victoria' : ['BLACKHORSE ROAD', 'BRIXTON', 'EUSTON', 'FINSBURY PARK', 'GREEN PARK', 'HIGHBURY', 'KINGS CROSS ST PANCRAS', 'OXFORD CIRCUS', 'PIMLICO', 'SEVEN SISTERS', 'STOCKWELL', 'TOTTENHAM HALE', 'VAUXHALL', 'VICTORIA', 'WALTHAMSTOW', 'WARREN STREET'],
                    'Walking' : ['ALDGATE', 'ALDGATE EAST', 'BANK', 'BARBICAN', 'BAYSWATER', 'CANONS PARK', 'CHANCERY LANE', 'EALING BROADWAY', 'EDGWARE', 'EUSTON', 'EUSTON SQUARE', 'FARRINGDON', 'GREAT PORTLAND STREET', 'HANGER LANE', 'ICKENHAM', 'KENTON', 'LANCASTER GATE', 'MANSION HOUSE', 'MONUMENT', 'NORTH EALING', 'NORTHWICK PARK', 'PADDINGTON', 'PARK ROYAL', 'QUEENSWAY', 'REGENTS PARK', 'ROYAL OAK', 'RUISLIP', 'SHEPHERDS BUSH', 'SHEPHERDS BUSH MARKET', 'ST PAULS', 'WARREN STREET', 'WARWICK AVENUE', 'WEST ACTON', 'WEST RUISLIP', 'WHITE CITY', 'WOOD LANE'],
                    'Waterloo & City' : ['BANK', 'WATERLOO']
                 }

           
